### ISSUE TITLE
Pairs of triples inverselly duplicated

### ISSUE THREAD

**Issue by DenisAraujo68** [Ensepro/ensepro-core#28]
It is being generated pairs of triples inversely duplicated.
For example:
Em que filmes Julia Roberts e Richard Gere atuaram?

> 0 - score:27.500 [_**+richard_gere | ocupacao | +ator**_ | _**+julia_roberts | ocupacao | +ator**_]
> 1 - score:27.500 [_**+julia_roberts | ocupacao | +ator**_ | _**+richard_gere | ocupacao | +ator**_]
> 2 - score:21.690 [+richard_gere | ocupacao | +ator | hachiko:_a_dog's_story | +producao | +richard_gere]
> 3 - score:21.333 [**pretty_woman | elenco | +richard_gere** | **pretty_woman | elenco | +julia_roberts**]  
> 4 - score:21.333 [**pretty_woman | elenco | +julia_roberts** | **pretty_woman | elenco | +richard_gere**]
> 5 - score:21.333 [**noiva_em_fuga | elenco | +richard_gere** | **noiva_em_fuga | elenco | +julia_roberts**]
> 6 - score:21.333 [**noiva_em_fuga | elenco | +julia_roberts** | **noiva_em_fuga | elenco | +richard_gere**]
> 7 - score:21.333 [**+richard_gere | nacionalidade | norte-americana** | **+julia_roberts | nacionalidade | norte-americana**]
> 8 - score:21.333 [**+julia_roberts | nacionalidade | norte-americana** | **+richard_gere | nacionalidade | norte-americana**]

**Comment by DenisAraujo68** [comment]
Another case:
- Mostre-me a autobiografia de Hemingway.
- Christian Bale atua em Batman Begins?

**Comment by alencarrh** [comment]
@DenisAraujo68 can you validate this issue, I think its fixed. Thanks.

**Comment by DenisAraujo68** [comment]
I tested now and the problem remains:
```
# ensepro -resposta -verbose -frase "Que livros de Kerouac foram publicados pela Viking Press?"
Analisando frase(s)...

Melhores respostas:
0 - score:21.333 [on_the_road | editora | *viking_press | on_the_road | autor | *jack_kerouac]   metrics: [20.000 0.333 1.000] metricsClass: [1.00(WORST_MATCH),1.00(BEST_MATCH),1.00(BEST_MATCH)]
1 - score:21.333 [on_the_road | autor | *jack_kerouac | on_the_road | editora | *viking_press]   metrics: [20.000 0.333 1.000] metricsClass: [1.00(WORST_MATCH),1.00(BEST_MATCH),1.00(BEST_MATCH)]

```

**Comment by DenisAraujo68** [comment]
This problem was solved in the implementation of the issue #43
