### ISSUE TITLE
Removing adjuncts only when they are Nouns or ADJectives

### ISSUE THREAD

**Issue by DenisAraujo68** [Ensepro/ensepro-core#47]
A bug was found on the algorithm when removing adjuncts in the question:
>Em que filmes Julia Roberts e Richard Gere atuaram?

The algorithm are removing words that alter the meaning of the sentence.
When an adjunct is identified, only **ADJ**ectives and common **N**ouns must be removed.

**Comment by DenisAraujo68** [comment]
What is happening is that when we call ENSEPRO with the sentence **Em que filmes Julia Roberts e Richard Gere atuaram?**, it is removing the conjunction **"e"** because this word is immediately before a PROP tagged with \<np-close>. Currently, if the system finds a PROP tagged with \<bp-close>, the term immediately before of the PROP is removed.
This rule, when applied to the phrase cited above, results in this sentence: 
- Em que filmes Julia Roberts Richard Gere atuaram?
This change in the phrase causes a mess because it makes Palavras think that **Julia Roberts Richard Gere** is a unique proper noun.

**Comment by DenisAraujo68** [comment]
the bug was fixed:

```
root@ensepro:~# ensepro -tr -original -frase "Em que filmes Julia Roberts e Richard Gere atuaram?"
Analisando frase(s)... 
-> Frase 1: Em que filmes Julia Roberts e Richard Gere atuaram?
--> Tipo: TipoFrase={tipo=em_que, confianca=0.85, ids=[3, 5]}
--> Voz: Voz.ATIVA
--> Termos Relevantes:
----> TR 0: [H:n|6| filmes]
----> TR 1: [CJT:prop|8| Julia_Roberts]
----> TR 2: [CJT:prop|10| Richard_Gere]
----> TR 3: [P:v-fin|11| atuaram]
root@ensepro:~# ensepro -tr -final -frase "Em que filmes Julia Roberts e Richard Gere atuaram?"
Analisando frase(s)... 
-> Frase 3:  Em que filmes <split> Julia_Roberts <split> <split> Richard_Gere <split> atuaram
--> Tipo: TipoFrase={tipo=em_que, confianca=0.85, ids=[3, 5]}
--> Voz: Voz.ATIVA
--> Termos Relevantes:
----> TR 0: [H:n|6| filmes]
----> TR 1: [H:prop|8| Julia_roberts]
----> TR 2: [DN:prop|9| Richard_gere]
----> TR 3: [P:v-fin|10| atuaram]
```

**Comment by DenisAraujo68** [comment]
I make a mistake closing this issue.
The problem remains: the conjunction "e" is being removed yet.
The insertion of the splits makes Palavras do not unify Julia_roberts and Richard_Gere, but the remotion of the conjunction "e" cause a sequence of problems that result in the wrong list of candidates.
We can see above that the conjunction "e" is removed from the phrase when we run ENSEPRO with the option "-final".
Because of this, I reopen this issue.

**Comment by DenisAraujo68** [comment]
I make a mistake closing this issue.
The problem remains: the conjunction **"e"** is yet being removed.
The insertion of the _splits_ makes Palavras do not unify Julia_roberts and Richard_Gere anymore, but the remotion of the conjunction **"e"** cause a sequence of errors that result in the wrong list of candidates.
We can see above that the conjunction **"e"** is beiinbg removed from the phrase when we run ENSEPRO with the option **"-final"**.
Because of this, I **reopen** this issue.

**Comment by alencarrh** [comment]
Hi @DenisAraujo68,

Please, do validate this issue, I think I fixed :)

```
root@ensepro:~/.../cbc# ensepro -frase "Em que filmes Julia Roberts e Richard Gere atuaram?" -resposta -final -tr
Analisando frase(s)...
-> Frase 2:  Em que filmes <split> Julia_Roberts <split> e <split> Richard_Gere <split> atuaram
--> Tipo: TipoFrase={tipo=em_que, confianca=0.85, ids=[3, 5]}
--> Voz: Voz.ATIVA
--> Termos Relevantes:
----> TR 0: [H:n|6| filmes]
----> TR 1: [CJT:prop|8| Julia_roberts]
----> TR 2: [CJT:prop|10| Richard_gere]
----> TR 3: [P:v-fin|11| atuaram]
```

**Comment by DenisAraujo68** [comment]
Yes, you are right, @alencarrh : it is fixed!
