### ISSUE TITLE
Increasing the coherence of the answers by reducing the ambiguity of the concepts

### ISSUE THREAD

**Issue by DenisAraujo68** [Ensepro/ensepro-core#48]
The probability of a match between the triple's elements and original or derivatives TRs could be increased by reducing the ambiguity of the concepts.
To clarify what was said above, we will analyze a concrete example.

> -> Frase 212: Quais são os cinco condados de New York?
> --> Termos Relevantes:
> ----> TR 0: [DN:num|6| cinco]
> --------> Sinonimos: {'por': [], 'eng': []}
> ----> TR 1: [H:n|7| **condados**]
> --------> Sinonimos: {'por': [província, país, domínio, Condado_dos_EUA, districto, circunscrição_administriva, território, colónia, região, Condados_do_Reino_Unido, bairro, **terra**, comarca, distrito, circunscrição, condado], 'eng': [county, shire, territorial_dominion, dominion, district, earldom, territory]}
> ----> TR 2: [DP:prop|10| Nova_iorque]
> --------> Sinonimos: {'por': [], 'eng': []}
> Melhores respostas:
> 0 - score:21.075 [**nova_iorque** | **condado** | bronx | **nova_iorque** | **areaterra** | 78383]   metrics: [19.575 0.500 1.000] metricsClass: [1.00(WORST_MATCH),1.00(BEST_MATCH),1.00(BEST_MATCH)]

We can see above that the pair of triples was selected as better answer because it contains matches with the TRs **Nova_iorque**, **condado** and **terra**. 
However, this triple isn't the better answer to the question. If we analyze the pair of triples, we can observe that there is an ambiguity of concepts in their matches: there is a match with the original TR **condado** in the first triple (_[nova_iorque| **condado** | bronx]_) and a partial match with the TR **terra** int the second triple (_ [nova_iorque | **areaterra** | 78383]_).
The ambiguity happens when a unique concept (**condado**) is assigned to two differents words (**condado** and **terra**) in the same answer.
If we assume that the concept "condado" is portrayed by the word "condado" in an answer, it is a misconception to assign this concept to another word into the same answer.
It is because of this misconception that the incorrect answer was select as the better candidate in the example above.

To avoid the misconception, we must to guarantee that when a concept is associated with a word, we will mantain the coherence in all the answer, ignoring matches that will weak this association.

If we follow this rule, the matches to question above would be:

> [**nova_iorque** | **condado** | bronx | **nova_iorque** | areaterra | 78383]

(i.e., the match with the derivative TR **terra** is ignored)

### Rules for priorization of the matches:
1. Matches with the original TR of the question will be prioritized: if a macth occur with the original TR of the question, this match will prevail above all others matches with derivative TRs.
2. If a match occurs first with a derivative TR and, after that, with a original TR, the former match will be ignored and the match with the original TR will prevail (as rule above states).
3. If a match occurs first with one of the derivatives TR and after with another derivative TR and both of them are synsets of Wordnet, the synset with lower number prevails over the another.
3. If a match occurs first with one of the derivatives TR and after with another derivative TR and **didn't** both of them are synsets of Wordnet, the former match will prevail and the last match will be ignored.

**Comment by DenisAraujo68** [comment]
Another question that the reinforcement of coherence should help to find the correct anwer:
- Qual a moeda da China?

**Comment by DenisAraujo68** [comment]
Question in wich the problem occurs (**IMPORTANT**: it is only to see if the implementation of the coherency works, once the coherence will not help to find the answer to this question):
- Qual é o maior país do mundo?

**Comment by DenisAraujo68** [comment]
@alencarrh we need to review the changes implemented to fix this issue. 
I see problems:
1. In the original question of the issue
- Quais são os cinco condados de New York?
Before the changes, ranking system counted twice, but now it totally ignore the `condado` TR:
```
root@ensepro:~# ensepro -resposta -frase "Quais são os cinco condados de New York?"
Melhores respostas:

Lista de triplas candidatas a resposta: 
0 11.333 [aaron_refvem | localidaden | *new_york] - [10.000 0.333 1.000]
1 11.333 [another_one | estudio | *new_york] - [10.000 0.333 1.000]
```

2. In this another example,seems the TR `moeda` isn't ranked. As you can see below, there are a triple with both TRs `moeda` and `china`:

```
root@ensepro:~# ensepro -resposta -frase "Qual a moeda da China?"
Melhores respostas:

Lista de triplas candidatas a resposta: 
0 11.333 [tiro_com_arco_nos_jogos_olimpicos_de_verao_de_2012___equipes_femininas | localmundial | *china] - [10.000 0.333 1.000]
1 11.333 [guangzhou_evergrande_taobao_football_club | local | *china] - [10.000 0.333 1.000]
...

>root@ensepro:~# grep -i "/china> <.*moeda" ~/DBPedia_2016-10/infobox_properties_*pt.ttl
/root/DBPedia_2016-10/infobox_properties_mapped_pt.ttl:<http://pt.dbpedia.org/resource/China> <http://pt.dbpedia.org/property/moeda> <http://pt.dbpedia.org/resource/Renminbi> .
```

**Comment by alencarrh** [comment]
Hello @DenisAraujo68 

Follow the result for all phrases you reported in this issue:
```
### root@ensepro:~# ensepro -frase "Quais são os cinco condados de New York?" -resposta
Melhores respostas:
0 12.958 [*west_new_york | *condado | *condado_de_hudson_(nova_jersei)] - [11.291 0.667 1.000]

Lista de triplas candidatas a resposta:
0 12.958 [*west_new_york | *condado | *condado_de_hudson_(nova_jersei)] - [11.291 0.667 1.000]
1 12.149 [*new_york_stories | elenco | *talia_shire] - [10.482 0.667 1.000]
2 12.005 [ilha_ellis | *regiao | *upper_new_york_bay] - [10.339 0.667 1.000]
3 11.786 [*un_divan_a_new_york | *pais | //] - [10.119 0.667 1.000]
4 11.333 [aaron_refvem | localidaden | *new_york] - [10.000 0.333 1.000]
[...]

### root@ensepro:~# ensepro -frase "Qual a moeda da China?" -resposta
Melhores respostas:
0 13.667 [*china | *moeda | renminbi] - [12.000 0.667 1.000]

Lista de triplas candidatas a resposta:
0 13.667 [*china | *moeda | renminbi] - [12.000 0.667 1.000]
1 13.542 [*china | *moedaiso | rmb] - [11.876 0.667 1.000]
2 13.399 [campeonato_mundial_de_natacao_em_piscina_curta_de_2014___4x200_m_livre_feminino | *prataatleta | *china] - [11.733 0.667 1.000]
3 13.346 [lassa | *subdivisaonome | *china] - [11.680 0.667 1.000]
4 13.346 [weifang | *subdivisaonome | *china] - [11.680 0.667 1.000]
[...]

### root@ensepro:~# ensepro -frase "Em que país nasce o Nilo?" -resposta
Melhores respostas:
0 15.003 [*nilopolis | *pais | brasil | farid_abrahao_david | *localnascimento | *nilopolis] - [13.503 0.500 1.000]
1 15.003 [*nilopolis | *pais | brasil | leonardo_picciani | *localnascimento | *nilopolis] - [13.503 0.500 1.000]

Lista de triplas candidatas a resposta:
0 15.003 [*nilopolis | *pais | brasil | farid_abrahao_david | *localnascimento | *nilopolis] - [13.503 0.500 1.000]
1 15.003 [*nilopolis | *pais | brasil | leonardo_picciani | *localnascimento | *nilopolis] - [13.503 0.500 1.000]
2 14.819 [*nilopolis | *mesorregiao | *mesorregiao_metropolitana_do_rio_de_janeiro | farid_abrahao_david | *localnascimento | *nilopolis] - [13.319 0.500 1.000]
3 14.819 [*nilopolis | *mesorregiao | *mesorregiao_metropolitana_do_rio_de_janeiro | leonardo_picciani | *localnascimento | *nilopolis] - [13.319 0.500 1.000]
4 14.775 [*nilopolis | *microrregiao | *microrregiao_do_rio_de_janeiro | farid_abrahao_david | *localnascimento | *nilopolis] - [13.275 0.500 1.000]
[...]

### root@ensepro:~# ensepro -frase "Qual é o maior país do mundo?" -resposta
Melhores respostas:
0 6.500 [*rio_grande_do_sul | lema | *liberdade, igualdade, humanidade | judaismo_no_brasil | *regiao | *rio_grande_do_sul] - [5.167 0.333 1.000]

Lista de triplas candidatas a resposta:
0 6.500 [*rio_grande_do_sul | lema | *liberdade, igualdade, humanidade | judaismo_no_brasil | *regiao | *rio_grande_do_sul] - [5.167 0.333 1.000]
1 6.433 [*augusto_pestana_(rio_grande_do_sul) | *datamicrorregiao | 2008 | *augusto_pestana_(rio_grande_do_sul) | *fimmandato | 2016] - [5.100 0.333 1.000]
2 6.433 [*augusto_pestana_(rio_grande_do_sul) | *fimmandato | 2016 | *augusto_pestana_(rio_grande_do_sul) | *datamicrorregiao | 2008] - [5.100 0.333 1.000]
3 6.344 [*grande_manchester | *distritos | 10 | joy_division | origem | *grande_manchester] - [5.010 0.333 1.000]
4 6.344 [*grande_manchester | *distritos | 10 | william_huskisson | mortelocal | *grande_manchester] - [5.010 0.333 1.000]
```
