### ISSUE TITLE
:num isn't a TR

### ISSUE THREAD

**Issue by DenisAraujo68** [Ensepro/ensepro-core#52]
When running this command:
`ensepro_main.py -tr -original  -frase "Quais são os cinco condados de Nova Iorque?"`

ENSEPRO returns that `cinco` is a TR, but it isn't:
> ----> TR 0: [DN:num|6| cinco]

**Expected behavior**
Don't classify `cinco` as TR.

**Log files**
[ensepro.log](https://github.com/Ensepro/ensepro-core/files/2594799/ensepro.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/31442514/48700966-4572f500-ebe5-11e8-9eb0-e740353f696b.png)

**Additional context**
Probably the problem is related to the REGEXP used to select the TRs.

**Comment by alencarrh** [comment]
Hi @DenisAraujo68 

issue resolved, please validate
```
root@ensepro:~/.../cbc# ensepro -frase "Quais são os cinco condados de Nova Iorque?" -tr -final
Analisando frase(s)...
-> Frase 1: Quais são os cinco condados de Nova Iorque?
--> Tipo: TipoFrase={tipo=qual, confianca=0.9, ids=[2]}
--> Voz: Voz.ATIVA
--> Termos Relevantes:
----> TR 0: [H:n|7| condados]
----> TR 1: [DP:prop|10| Nova_Iorque]
```

**Comment by DenisAraujo68** [comment]
I tested and it is running as expected.
