### ISSUE TITLE
Don't import gensim when not using -resposta option

### ISSUE THREAD

**Issue by DenisAraujo68** [Ensepro/ensepro-core#60]
The time to load gensim is significant.

If ENSEPRO was not called with the `-resposta`, so we don't need to import gensim classes.

Change the code to not load gensim when it isn't necessary.

**Comment by alencarrh** [comment]
Hi @DenisAraujo68 

yes, i forgot that it shouldn't load the models vector for gensim every time.

it should be fixed now. The model vector will only be loaded if you pass the param `-resposta` or `-verbose`
