### ISSUE TITLE
TR goes away

### ISSUE THREAD

**Issue by DenisAraujo68** [Ensepro/ensepro-core#61]
A TR goes away when running ENSEPRO.

1. Use ENSEPRO with the configs.json with marco_triplas ES index (file attached)
2. Run: `ensepro  -frase "Quais os sintomas que o paciente Marie Syamala relata?" -tr -original` to see that `paciente` is a TR
3. Run: `ensepro  -frase "Quais os sintomas que o paciente Marie Syamala relata?" -tr -final` to see that `paciente` goes away

**Expected behavior**
The TR `paciente` must be used to rank the answers, what doesn't happen now:

> root@ensepro:~# ensepro -resposta  -frase "Quais os sintomas que o **paciente** Marie Syamala relata?" -tr -original
> Analisando frase(s)... 
> -> Frase 1: Quais os sintomas que o **paciente** Marie Syamala relata?
> --> Tipo: TipoFrase={tipo=qual, confianca=0.9, ids=[3]}
> --> Voz: Voz.ATIVA
> --> Termos Relevantes:
> ----> TR 0: [H:n|6| sintomas]
> ----> TR 1: [H:n|11| **paciente**]
> ----> TR 2: [DN:prop|12| Marie_Syamala]
> ----> TR 3: [P:v-fin|13| relata]
> 
> Melhores respostas:
> 0 11.333 [*marie_syamala | possui | evolucao_201704111602] - [10.000 0.333 1.000]
> 1 11.333 [*marie_syamala | possui | evolucao_201705151342] - [10.000 0.333 1.000]
> 
> Lista de triplas candidatas a resposta: 
> 0 11.333 [*marie_syamala | type | namedindividual] - [10.000 0.333 1.000]
> 1 11.333 [*marie_syamala | type | **paciente**] - [10.000 0.333 1.000]
> 2 11.333 [*marie_syamala | paciente_id | <12> .] - [10.000 0.333 1.000]
 
**Log files**
[ensepro.log](https://github.com/Ensepro/ensepro-core/files/2817401/ensepro.log)

**Additional context**
The bug reported in this issue occurs with the marco_triplas index, so the config file below must be used
[configs.json.txt](https://github.com/Ensepro/ensepro-core/files/2817400/configs.json.txt)

**Comment by alencarrh** [comment]
Hi @DenisAraujo68 

Right, only looking at the files, we can see this:
```
2019-01-31 11:14:04,041 - ensepro - INFO - Frase processada: [frase=Frase={id=2, palavras=[, , Quais, , os, sintomas, , que, , o, paciente, Marie_Syamala, relata, ], tipo=None, locucao_verbal=None, voz=None}]
2019-01-31 11:14:04,041 - ensepro.cbc - INFO - Removendo adjuntos adnominais justapostos
2019-01-31 11:14:04,041 - ensepro.cbc - INFO - Removendo adjunto nominal: [H:n|11| paciente]
2019-01-31 11:14:04,042 - ensepro.cbc - INFO - Frase após remoção adjunto adnominais justapostos:  Quais os sintomas que o <split> Marie_Syamala <split> relata
2019-01-31 11:14:04,042 - ensepro - INFO - Iniciando processamento: [frase_id=3, frase= Quais os sintomas que o <split> Marie_Syamala <split> relata]
```
We can see that `[H:n|11| paciente]` is matching the rules of **adjuntos adnominais justapostos**.
The rule is:

```python3
for word in phrase.words: # iterates in the reverse other
    if word is proper_noun and "<np-close>" in word.tags:
        # ignore the next word (as the iteration is in reverse, is the previous word)
```

Running like this, we can see exactly that rule:
```
ensepro -frase "Quais os sintomas que o paciente Marie Syamala relata?" -original -tags

Analisando frase(s)...
-> Frase 1: Quais os sintomas que o paciente Marie Syamala relata?
--> Tipo: TipoFrase={tipo=qual, confianca=0.9, ids=[3]}
--> Voz: Voz.ATIVA
--> Tags das palavras
----> Palavra[  1]                      -                     ==> []
----> Palavra[  2]                      -                     ==> []
----> Palavra[  3]                Quais - qual                ==> ['<clb>', '<*>', '<interr>', 'DET', 'M/F', 'P']
----> Palavra[  4]                      -                     ==> []
----> Palavra[  5]                   os - o                   ==> ['<artd>', 'M', 'P']
----> Palavra[  6]             sintomas - sintoma             ==> ['<sick-c>', 'F', 'P']
----> Palavra[  7]                      -                     ==> []
----> Palavra[  8]                  que - que                 ==> ['<clb>', '<interr>', 'M', 'S']
----> Palavra[  9]                      -                     ==> []
----> Palavra[ 10]                    o - o                   ==> ['<artd>', 'M', 'S']
----> Palavra[ 11]             paciente - paciente            ==> ['<H>', 'M', 'S']
----> Palavra[ 12]        Marie_Syamala - Marie_Syamala       ==> ['<hum>', '<*>', '<foreign>', '<np-close>', 'F', 'S']
----> Palavra[ 13]               relata - relatar             ==> ['<fmc>', '<vH>', '<mv>', 'PR', '3S', 'IND', 'VFIN']

```

Well, so what we can do is review the **adjuntos adnominais justapostos** rules.

**Comment by DenisAraujo68** [comment]
I got it, @alencarrh.
The word `paciente` acting as an adnominal adjunct in this phrase and we decided to throw away the adjuncts.
For this ontology, the adjuncts would help to find the correct answer.
Well, we will not change the ENSEPRO's code because of this now.
I'll close this issue.
