### ISSUE TITLE
Answer selection algorithm failed to detect the need of the use of the word embeddings

### ISSUE THREAD

**Issue by DenisAraujo68** [Ensepro/ensepro-core#63]
**Describe the bug**
The answer selection algorithm should detect the need of word embeddings to select the correct answer.

**To Reproduce**
1. use /root/ENSEPRO-DBPedia-configs.json config file
2. run `ensepro -resposta -frase "Quando começou a Operação Overlord?"`

**Expected behavior**
Activate word embeddings answer selection algorithm.

**Screenshots**

> 
> root@ensepro:~# ensepro -resposta -frase "Quando começou a Operação Overlord?"
> 
> Melhores respostas:
> 0 11.333 [leonard_lomell | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
> 1 11.333 [operacao_spring | conflito | *operacao_overlord] - [10.000 0.333 1.000]
> 2 11.333 [robert_wynn | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
> 3 11.333 [eberhard_thunert | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
> 4 11.333 [projeto_manhattan | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
> 5 11.333 [*operacao_overlord | imagem | normandysupply edit.jpg] - [10.000 0.333 1.000]
> 6 11.333 [*operacao_overlord | data | 6] - [10.000 0.333 1.000]
> 7 11.333 [*operacao_overlord | editor1last | dear] - [10.000 0.333 1.000]
> 8 11.333 [*operacao_overlord | editor1link | i. c. b. dear] - [10.000 0.333 1.000]
> 9 11.333 [*operacao_overlord | origyear | 1995] - [10.000 0.333 1.000]
> 10 11.333 [*operacao_overlord | title | --06-25] - [10.000 0.333 1.000]
> 11 11.333 [*operacao_overlord | title | les luxembourgeois de la \"brigade piron\"] - [10.000 0.333 1.000]
> 12 11.333 [*operacao_overlord | title | the oxford companion to world war ii] - [10.000 0.333 1.000]
> 13 11.333 [*operacao_overlord | work | frequently asked questions] - [10.000 0.333 1.000]
> 14 11.333 [*operacao_overlord | comandante | erwin rommel] - [10.000 0.333 1.000]
> 15 11.333 [*operacao_overlord | comandante | bernard montgomery] - [10.000 0.333 1.000]
> 16 11.333 [*operacao_overlord | comandante | gerd_von_rundstedt] - [10.000 0.333 1.000]
> 17 11.333 [*operacao_overlord | comandante | bertram ramsay] - [10.000 0.333 1.000]
> 18 11.333 [*operacao_overlord | comandante | trafford leigh-mallory] - [10.000 0.333 1.000]
> 19 11.333 [*operacao_overlord | comandante | arthur tedder] - [10.000 0.333 1.000]
> 20 11.333 [*operacao_overlord | comandante | dwight_d._eisenhower] - [10.000 0.333 1.000]
> 21 11.333 [*operacao_overlord | for | 2052299] - [10.000 0.333 1.000]
> 22 11.333 [*operacao_overlord | for | 2200] - [10.000 0.333 1.000]
> 23 11.333 [*operacao_overlord | for | 1452000] - [10.000 0.333 1.000]
> 24 11.333 [*operacao_overlord | for | 380000] - [10.000 0.333 1.000]
> 25 11.333 [*operacao_overlord | baixas | ~4.000 tanques] - [10.000 0.333 1.000]
> 26 11.333 [*operacao_overlord | baixas | 226386] - [10.000 0.333 1.000]
> 27 11.333 [*operacao_overlord | baixas | 4101] - [10.000 0.333 1.000]
> 28 11.333 [*operacao_overlord | baixas | 400000] - [10.000 0.333 1.000]
> 29 11.333 [*operacao_overlord | baixas | ~2.200 tanques e canhoes] - [10.000 0.333 1.000]
> 30 11.333 [*operacao_overlord | baixas | 2127] - [10.000 0.333 1.000]
> 31 11.333 [walter_gordon | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
> 32 11.333 [*operacao_overlord | notas | 11000] - [10.000 0.333 1.000]
> 33 11.333 [*operacao_overlord | notas | mortes de civis:] - [10.000 0.333 1.000]
> 34 11.333 [*operacao_overlord | notas | 13632] - [10.000 0.333 1.000]
> 35 11.333 [*operacao_overlord | local | normandia] - [10.000 0.333 1.000]
> 36 11.333 [*operacao_overlord | local | franca] - [10.000 0.333 1.000]
> 37 11.333 [*operacao_overlord | local | cranfield, bedford] - [10.000 0.333 1.000]
> 38 11.333 [*operacao_overlord | legenda | navios de desembarque descarregando tanques e suprimentos na praia de omaha na normandia.] - [10.000 0.333 1.000]
> 39 11.333 [*operacao_overlord | editor1first | i.c.b.] - [10.000 0.333 1.000]
> 40 11.333 [*operacao_overlord | editor2first | m.r.d.] - [10.000 0.333 1.000]
> 41 11.333 [*operacao_overlord | ref | harv] - [10.000 0.333 1.000]
> 42 11.333 [*operacao_overlord | titulo | the development of british civil affairs and its employment in the british sector of allied military operations during the battle of normandy, june to august 1944] - [10.000 0.333 1.000]
> 43 11.333 [*operacao_overlord | url | brigade_piron.php] - [10.000 0.333 1.000]
> 44 11.333 [*operacao_overlord | url | faq109_1.htm] - [10.000 0.333 1.000]
> 45 11.333 [*operacao_overlord | ultimo | flint] - [10.000 0.333 1.000]
> 46 11.333 [burton_p._christenson | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
> 47 11.333 [*operacao_overlord | primeiro | edward r] - [10.000 0.333 1.000]
> 48 11.333 [*operacao_overlord | author | us department of the navy, naval history and heritage command] - [10.000 0.333 1.000]
> 49 11.333 [*operacao_overlord | author | government of luxembourg] - [10.000 0.333 1.000]
> 50 11.333 [*operacao_overlord | conflito | parte da frente ocidental da segunda guerra mundial] - [10.000 0.333 1.000]
> 51 11.333 [*operacao_overlord | transtitle | the luxembourg \"brigade piron\"] - [10.000 0.333 1.000]
> 52 11.333 [*operacao_overlord | editor2link | m. r. d. foot] - [10.000 0.333 1.000]
> 53 11.333 [*operacao_overlord | location | oxford; new york] - [10.000 0.333 1.000]
> 54 11.333 [*operacao_overlord | ano | 2009] - [10.000 0.333 1.000]
> 55 11.333 [earl_mcclung | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
> 56 11.333 [*operacao_overlord | grau | ph.d.] - [10.000 0.333 1.000]
> 57 11.333 [*operacao_overlord | editor | cranfield university; cranfield defence and security school, department of applied science, security and resilience, security and resilience group] - [10.000 0.333 1.000]
> 58 11.333 [*operacao_overlord | oclc | 757064836] - [10.000 0.333 1.000]
> 59 11.333 [*operacao_overlord | text | voces estao prestes a embarcar na grande cruzada, para o qual temos lutando todos esses meses. os olhos do mundo estao sobre voces. as esperancas e oracoes de pessoas amantes da liberdade em toda parte marcham com voces. em companhia de nossos bravos aliados e irmaos de armas em outras frentes, voces vao trazer a destruicao da maquina de guerra alema, a eliminacao da tirania nazista sobre os povos oprimidos da europa, e seguranca para nos mesmos em um mundo livre.] - [10.000 0.333 1.000]
> 60 11.333 [*operacao_overlord | sign | dwight d. eisenhower] - [10.000 0.333 1.000]
> 61 11.333 [*operacao_overlord | editor2last | foot] - [10.000 0.333 1.000]
> 62 11.333 [*operacao_overlord | publisher | oxford university press] - [10.000 0.333 1.000]
> 63 11.333 [*operacao_overlord | isbn | 978] - [10.000 0.333 1.000]
> 64 11.333 [*operacao_overlord | nome | operacao overlord] - [10.000 0.333 1.000]
> 65 11.333 [friedrich_adrario | guerras | *operacao_overlord] - [10.000 0.333 1.000]
> 66 11.333 [*operacao_overlord | source | carta para as forcas aliadas] - [10.000 0.333 1.000]
> 67 11.333 [*operacao_overlord | year | 2005] - [10.000 0.333 1.000]
> 68 11.333 [*operacao_overlord | accessdate | 29] - [10.000 0.333 1.000]
> 69 11.333 [primo_victoria | extra | *operacao_overlord] - [10.000 0.333 1.000]
> 70 11.333 [*operacao_overlord | resultado | vitoria decisiva aliada] - [10.000 0.333 1.000]
> 71 11.333 [joseph_liebgott | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
> 72 11.333 [operacao_cobra | conflito | *operacao_overlord] - [10.000 0.333 1.000]
> 73 11.333 [alton_moore | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
> 74 11.333 [bolsa_de_falaise | conflito | *operacao_overlord] - [10.000 0.333 1.000]
> 75 11.333 [james_h._alley,_jr. | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
> 
> Lista de triplas candidatas a resposta: 
> 0 11.333 [leonard_lomell | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
> 1 11.333 [operacao_spring | conflito | *operacao_overlord] - [10.000 0.333 1.000]
> 2 11.333 [robert_wynn | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
> 3 11.333 [eberhard_thunert | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
> 4 11.333 [projeto_manhattan | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
> 5 11.333 [*operacao_overlord | imagem | normandysupply edit.jpg] - [10.000 0.333 1.000]
> 6 11.333 [*operacao_overlord | data | 6] - [10.000 0.333 1.000]
> 7 11.333 [*operacao_overlord | editor1last | dear] - [10.000 0.333 1.000]
> 8 11.333 [*operacao_overlord | editor1link | i. c. b. dear] - [10.000 0.333 1.000]
> 9 11.333 [*operacao_overlord | origyear | 1995] - [10.000 0.333 1.000]
> 10 11.333 [*operacao_overlord | title | --06-25] - [10.000 0.333 1.000]
> 11 11.333 [*operacao_overlord | title | les luxembourgeois de la \"brigade piron\"] - [10.000 0.333 1.000]
> 12 11.333 [*operacao_overlord | title | the oxford companion to world war ii] - [10.000 0.333 1.000]
> 13 11.333 [*operacao_overlord | work | frequently asked questions] - [10.000 0.333 1.000]
> 14 11.333 [*operacao_overlord | comandante | erwin rommel] - [10.000 0.333 1.000]
> 15 11.333 [*operacao_overlord | comandante | bernard montgomery] - [10.000 0.333 1.000]
> 16 11.333 [*operacao_overlord | comandante | gerd_von_rundstedt] - [10.000 0.333 1.000]
> 17 11.333 [*operacao_overlord | comandante | bertram ramsay] - [10.000 0.333 1.000]
> 18 11.333 [*operacao_overlord | comandante | trafford leigh-mallory] - [10.000 0.333 1.000]
> 19 11.333 [*operacao_overlord | comandante | arthur tedder] - [10.000 0.333 1.000]
> 20 11.333 [*operacao_overlord | comandante | dwight_d._eisenhower] - [10.000 0.333 1.000]
> 21 11.333 [*operacao_overlord | for | 2052299] - [10.000 0.333 1.000]
> 22 11.333 [*operacao_overlord | for | 2200] - [10.000 0.333 1.000]
> 23 11.333 [*operacao_overlord | for | 1452000] - [10.000 0.333 1.000]
> 24 11.333 [*operacao_overlord | for | 380000] - [10.000 0.333 1.000]
> 25 11.333 [*operacao_overlord | baixas | ~4.000 tanques] - [10.000 0.333 1.000]
> 26 11.333 [*operacao_overlord | baixas | 226386] - [10.000 0.333 1.000]
> 27 11.333 [*operacao_overlord | baixas | 4101] - [10.000 0.333 1.000]
> 28 11.333 [*operacao_overlord | baixas | 400000] - [10.000 0.333 1.000]
> 29 11.333 [*operacao_overlord | baixas | ~2.200 tanques e canhoes] - [10.000 0.333 1.000]
> 30 11.333 [*operacao_overlord | baixas | 2127] - [10.000 0.333 1.000]
> 31 11.333 [walter_gordon | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
> 32 11.333 [*operacao_overlord | notas | 11000] - [10.000 0.333 1.000]
> 33 11.333 [*operacao_overlord | notas | mortes de civis:] - [10.000 0.333 1.000]
> 34 11.333 [*operacao_overlord | notas | total: 25.00039.000 mortos] - [10.000 0.333 1.000]
> 35 11.333 [*operacao_overlord | notas | 13632] - [10.000 0.333 1.000]
> 36 11.333 [*operacao_overlord | local | normandia] - [10.000 0.333 1.000]
> 37 11.333 [*operacao_overlord | local | franca] - [10.000 0.333 1.000]
> 38 11.333 [*operacao_overlord | local | cranfield, bedford] - [10.000 0.333 1.000]
> 39 11.333 [*operacao_overlord | legenda | navios de desembarque descarregando tanques e suprimentos na praia de omaha na normandia.] - [10.000 0.333 1.000]
> 40 11.333 [*operacao_overlord | editor1first | i.c.b.] - [10.000 0.333 1.000]
> 41 11.333 [*operacao_overlord | editor2first | m.r.d.] - [10.000 0.333 1.000]
> 42 11.333 [*operacao_overlord | ref | harv] - [10.000 0.333 1.000]
> 43 11.333 [*operacao_overlord | titulo | the development of british civil affairs and its employment in the british sector of allied military operations during the battle of normandy, june to august 1944] - [10.000 0.333 1.000]
> 44 11.333 [*operacao_overlord | url | brigade_piron.php] - [10.000 0.333 1.000]
> 45 11.333 [*operacao_overlord | url | faq109_1.htm] - [10.000 0.333 1.000]
> 46 11.333 [*operacao_overlord | ultimo | flint] - [10.000 0.333 1.000]
> 47 11.333 [burton_p._christenson | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
> 48 11.333 [*operacao_overlord | primeiro | edward r] - [10.000 0.333 1.000]
> 49 11.333 [*operacao_overlord | author | us department of the navy, naval history and heritage command] - [10.000 0.333 1.000]
> 50 11.333 [*operacao_overlord | author | government of luxembourg] - [10.000 0.333 1.000]
> 51 11.333 [*operacao_overlord | conflito | parte da frente ocidental da segunda guerra mundial] - [10.000 0.333 1.000]
> 52 11.333 [*operacao_overlord | transtitle | the luxembourg \"brigade piron\"] - [10.000 0.333 1.000]
> 53 11.333 [*operacao_overlord | editor2link | m. r. d. foot] - [10.000 0.333 1.000]
> 54 11.333 [*operacao_overlord | location | oxford; new york] - [10.000 0.333 1.000]
> 55 11.333 [*operacao_overlord | ano | 2009] - [10.000 0.333 1.000]
> 56 11.333 [earl_mcclung | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
> 57 11.333 [*operacao_overlord | grau | ph.d.] - [10.000 0.333 1.000]
> 58 11.333 [*operacao_overlord | editor | cranfield university; cranfield defence and security school, department of applied science, security and resilience, security and resilience group] - [10.000 0.333 1.000]
> 59 11.333 [*operacao_overlord | oclc | 757064836] - [10.000 0.333 1.000]
> 60 11.333 [*operacao_overlord | campanha | europa ocidental 19441945] - [10.000 0.333 1.000]
> 61 11.333 [*operacao_overlord | text | voces estao prestes a embarcar na grande cruzada, para o qual temos lutando todos esses meses. os olhos do mundo estao sobre voces. as esperancas e oracoes de pessoas amantes da liberdade em toda parte marcham com voces. em companhia de nossos bravos aliados e irmaos de armas em outras frentes, voces vao trazer a destruicao da maquina de guerra alema, a eliminacao da tirania nazista sobre os povos oprimidos da europa, e seguranca para nos mesmos em um mundo livre.] - [10.000 0.333 1.000] ...

**Comment by alencarrh** [comment]
Hi @DenisAraujo68 

the problem of  `word_embedding` not working was fixed, please validate :)

```
root@ensepro:~/.../ensepro-core# ensepro -frase "Quando começou a Operação Overlord?" -tr -resposta -final
Analisando frase(s)...
-> Frase 1: Quando começou a Operação Overlord?
--> Tipo: TipoFrase={tipo=quando, confianca=0.91, ids=[2]}
--> Voz: Voz.ATIVA
--> Termos Relevantes:
----> TR 0: [P:v-fin|3| começou]
----> TR 1: [H:prop|6| Operação_Overlord]

Melhores respostas:
0 11.333 [primo_victoria | extra | *operacao_overlord] - [10.000 0.333 1.000]

Lista de triplas candidatas a resposta:
0 11.333 [leonard_lomell | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
1 11.333 [operacao_spring | conflito | *operacao_overlord] - [10.000 0.333 1.000]
2 11.333 [robert_wynn | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
3 11.333 [eberhard_thunert | batalhas | *operacao_overlord] - [10.000 0.333 1.000]
[...]
```

**Comment by DenisAraujo68** [comment]
I tested and all worked as expected.
So, I'm closing this issue.

**Comment by DenisAraujo68** [comment]
I remembered now that I can't close issues.
Reopening it and putting it in the review column.
