### ISSUE TITLE
Error when showing the list of candidates

### ISSUE THREAD

**Issue by DenisAraujo68** [Ensepro/ensepro-core#64]
**Describe the bug**
Error issued when running ENSEPRO to the question:
- Quem desenvolveu o Slack?

**To Reproduce**
1. Use config file /root/ENSEPRO-DBPedia-configs.json
2. run `ensepro -resposta -frase "Quem desenvolveu o Slack?"`

**Expected behavior**
Show all list of answers candidates without error message.

**Log files**
[ensepro.log](https://github.com/Ensepro/ensepro-core/files/2824870/ensepro.log)

**Screenshots**

> root@ensepro:~# ensepro -resposta -frase "Quem desenvolveu o Slack?"
> Analisando frase(s)... 
> 
> Melhores respostas:
> 0 9.996 [teen_titans:_trouble_in_tokyo | producao | *david slack] - [8.663 0.333 1.000]
> 
> Lista de triplas candidatas a resposta: 
> 0 10.712 [liga_dos_campeoes_da_uefa_de_futebol_feminino_de_201415 | gols | *islacker] - [9.379 0.333 1.000]
> 1 10.712 [campeonato_mundial_de_futebol_sub_17_de_2015 | gols | *passlack] - [9.379 0.333 1.000]
> 2 10.712 [international_champions_cup_de_2016 | penalidades | *passlack] - [9.379 0.333 1.000]
> .
> .
> .
> 73 3.333 [akregator | *desenvolvedor | *desenvolvedores akregator] - [3.000 0.333 0.000]
> 74 3.333 [lockheed_p_2_neptune | *desenvolvimento | l_188_electra] - [3.000 0.333 0.000]
> 
> 
> sequence item 2: expected str instance, int found
> root@ensepro:~#

**Comment by DenisAraujo68** [comment]
The problem also happens with "Quem é o prefeito da capital da Polinésia Francesa?"

**Log files**
[ensepro.log](https://github.com/Ensepro/ensepro-core/files/2826989/ensepro.log)

**Screenshots**

> root@ensepro:~# ensepro -resposta -frase "Qual o nome do prefeito da capital da Polinésia Francesa?"
> Analisando frase(s)... 
> 
> Melhores respostas:
> 
> Lista de triplas candidatas a resposta: 
> 0 27.656 [libreville | lidertitulo | prefeito | *congo_frances | *capital | libreville] - [24.822 0.833 2.000]
> 1 27.656 [porto_novo_(benim) | lidertitulo | prefeito | *daome_frances | *capital | porto_novo_(benim)] - [24.822 0.833 2.000]
> ...
> 61 23.507 [porto_novo_(benim) | subdivisaotipo | subdivisoes_do_benim | *daome_frances | *capital | porto_novo_(benim)] - [21.007 0.500 2.000]
> 
> **sequence item 2: expected str instance, int found**
> root@ensepro:~#

**Comment by alencarrh** [comment]
Hi @DenisAraujo68 

This problem was fixed at https://github.com/Ensepro/ensepro-core/commit/cea6f434cb5974ead9353d6ee732d6928b00dd7b
