### ISSUE TITLE
Amazon Eve replaced by Eve Torres

### ISSUE THREAD

**Issue by DenisAraujo68** [Ensepro/ensepro-core#65]
**Describe the bug**
The Spotlight algorithm is removing the correct entity from the sentence.

**To Reproduce**
1. Use DBPedia config
2. run `ensepro -resposta -frase "Qual a altura de Amazon Eve?"`

**Expected behavior**
"Amazon Eve" shouldn't be replaced by "Eve Torres"  since Spotlight says that only "Eve" was recognized as an entity.
When only part of the PROP is recognized as an entity, it's pretty reasonable to suppose that the Spotlight did a mistake.

**Log files**
[ensepro.log](https://github.com/Ensepro/ensepro-core/files/2825806/ensepro.log)

**Screenshots**

```
root@ensepro:~/.../qald2# ensepro -frase "Qual a altura de Amazon Eve?" -tr -original
Analisando frase(s)... 
-> Frase 1: Qual a altura de Amazon Eve?
--> Tipo: TipoFrase={tipo=qual, confianca=0.64, ids=[2]}
--> Voz: Voz.ATIVA
--> Termos Relevantes:
----> TR 0: [H:n|5| altura]
----> TR 1: [DP:prop|8| Amazon_Eve]

root@ensepro:~/.../qald2# ensepro -frase "Qual a altura de Amazon Eve?" -tr -final
Analisando frase(s)... 
-> Frase 3:  Qual a altura de <split> Eve_torres <split>
--> Tipo: TipoFrase={tipo=qual, confianca=0.59, ids=[2]}
--> Voz: Voz.ATIVA
--> Termos Relevantes:
----> TR 0: [H:n|5| altura]
----> TR 1: [DP:prop|8| Eve_torres]
```

**Comment by DenisAraujo68** [comment]
Rising the priority because of another occurrence of this bug:
```

root@ensepro:~# ensepro -tr -original -frase "Quem foi chamado de Frank The Tank?"
Analisando frase(s)... 
-> Frase 1: Quem foi chamado de Frank The Tank?
--> Tipo: TipoFrase={tipo=quem, confianca=0.93, ids=[2]}
--> Voz: Voz.ATIVA
--> Termos Relevantes:
----> TR 0: [Vm:v-pcp|5| chamado]
----> TR 1: [DP:prop|8| Frank_The_Tank]

root@ensepro:~# ensepro -tr -final -frase "Quem foi chamado de Frank The Tank?"
Analisando frase(s)... 
-> Frase 3:  Quem foi chamado de <split> Tank_paquistão <split>
--> Tipo: TipoFrase={tipo=quem, confianca=0.78, ids=[2]}
--> Voz: Voz.ATIVA
--> Termos Relevantes:
----> TR 0: [Vm:v-pcp|5| chamado]
----> TR 1: [DP:prop|8| Tank_paquistão]
```

**Comment by DenisAraujo68** [comment]
Another phrase to test:
- Quem é o prefeito da capital da Polinésia Francesa?

> 2019-02-04 05:32:34,878 - ensepro.cbc - INFO - Atualizando frase.
> 2019-02-04 05:32:34,878 - ensepro.cbc - DEBUG - Atualizando substantivo próprio ([H:prop|20| Polinésia_Francesa])com action: encontrar_entidade_spotlight_pt
> 2019-02-04 05:32:34,878 - ensepro.cbc - DEBUG - Buscando substantivo próprio no Spotlight-PT
> 2019-02-04 05:32:34,878 - ensepro.servicos.dbpedia_spotlight_service - INFO - Service Spotlight request: [request={'text': 'Qual o nome do prefeito da capital da Polinésia Francesa?', 'confidence': 0.3, 'support': 0}]
> 2019-02-04 05:32:34,890 - ensepro.servicos.dbpedia_spotlight_service - INFO - Service Spotlight response: [response=<Response [200]>]
> 2019-02-04 05:32:34,891 - ensepro.cbc - DEBUG - Response with confidence: 0.3
> 2019-02-04 05:32:34,891 - ensepro.cbc - DEBUG - Resultado da action (encontrar_entidade_spotlight_pt): {'nova_frase': 'Qual o nome do prefeito da capital da **\<split> Polinésia \<split>** Francesa?'}
>

**Comment by DenisAraujo68** [comment]
The closing of this issue was a mistake of mine

**Comment by DenisAraujo68** [comment]
The closing of this issue was a mistake of mine

**Comment by alencarrh** [comment]
Hello @DenisAraujo68 

This *bug* is from the implementation of this task https://github.com/Ensepro/ensepro-core/issues/10.
If we fix this, I'll have to remove the implementation of this feature (the `<split>` still going to be placed but the recognition that dbpedia spotlight returned more than one entity will need to be removed).

Important to remember that the validation if the entity returned from dbpedia spotlight exists in elasticsearch was removed.

**Comment by DenisAraujo68** [comment]
It's better we talk about this issue to decide what to do, @alencarrh

**Comment by DenisAraujo68** [comment]
@alencarrh 
We had agreed that we will only change the Spotlight confidence to 0.8 to fix the Amazon Eve problem, but now another problem arose: the book Os Pilares da Terra.
Currently, this is happening:

> -> Frase 3:  Quem escreveu o livro <split> Os_Pilares <split> de a <split> Terra <split>
> --> Tipo: TipoFrase={tipo=quem, confianca=0.78, ids=[2]}
> --> Voz: Voz.ATIVA
> --> Termos Relevantes:
> ----> TR 0: [P:v-fin|3| escreveu]
> ----> TR 1: [H:n|6| livro]
> ----> TR 2: [H:prop|8| Os_pilares]
> ----> TR 3: [H:prop|13| Terra]

Again Spotlight says to split the PROP and this makes ENSEPRO doesn't find the correct answer.
Maybe we should verify if the PROP exists in the ES before to activate Spotlight.
What do you think?

**Comment by DenisAraujo68** [comment]
Other case:

> Analisando frase(s)... 
> -> Frase 1: Que rio a Ponte do Brooklyn cruza?
> --> Tipo: TipoFrase={tipo=qual, confianca=0.85, ids=[3]}
> --> Voz: Voz.ATIVA
> --> Termos Relevantes:
> ----> TR 0: [H:n|4| rio]
> ----> TR 1: [H:prop|7| Ponte_do_Brooklyn]
> ----> TR 2: [P:v-fin|8| cruza]
> 
> root@ensepro:~# ensepro -tr -final -frase "Que rio a Ponte do Brooklyn cruza?"
> Analisando frase(s)... 
> -> Frase 2: Que rio a Ponte do <split> Brooklyn <split> cruza?
> --> Tipo: TipoFrase={tipo=qual, confianca=0.85, ids=[3]}
> --> Voz: Voz.ATIVA
> --> Termos Relevantes:
> ----> TR 0: [H:n|4| rio]
> ----> TR 1: [H:n|7| Ponte]
> ----> TR 2: [H:prop|12| Brooklyn]
> ----> TR 3: [P:v-fin|13| cruza]
>

**Comment by alencarrh** [comment]
Hi @DenisAraujo68 

> Maybe we should verify if the PROP exists in the ES before to activate Spotlight.
> What do you think?
Yes, I agree.

I did the fix and already updated semantics with it. Now befere changing/updating any **proper nouns** it will check to see if the **proper nouns** existis or not in elasticsearch and only will call DBPedia Spotlight if it doesn't.

The new results for the phrases you commented:
```
root@ensepro-core# ensepro -frase "Qual a altura de Amazon Eve?" -tr -final
Analisando frase(s)...
-> Frase 2: Qual a altura de Amazon Eve?
--> Tipo: TipoFrase={tipo=qual, confianca=0.64, ids=[2]}
--> Voz: Voz.ATIVA
--> Termos Relevantes:
----> TR 0: [H:n|5| altura]
----> TR 1: [DP:prop|8| Amazon_Eve]

root@ensepro-core# ensepro -frase "Que rio a Ponte do Brooklyn cruza?" -tr -final
Analisando frase(s)...
-> Frase 1: Que rio a Ponte do Brooklyn cruza?
--> Tipo: TipoFrase={tipo=qual, confianca=0.85, ids=[3]}
--> Voz: Voz.ATIVA
--> Termos Relevantes:
----> TR 0: [H:n|4| rio]
----> TR 1: [H:prop|7| Ponte_do_Brooklyn]
----> TR 2: [P:v-fin|8| cruza]

root@ensepro-core# ensepro -frase "Quem escreveu o livro Os Pilares da Terra?" -tr -final
Analisando frase(s)...
-> Frase 2:  Quem escreveu o <split> Os_Pilares_da_Terra <split>
--> Tipo: TipoFrase={tipo=quem, confianca=0.78, ids=[2]}
--> Voz: Voz.ATIVA
--> Termos Relevantes:
----> TR 0: [P:v-fin|3| escreveu]
----> TR 1: [H:prop|6| Os_pilares_da_terra]

root@ensepro-core# ensepro -frase "Quem é o prefeito da capital da Polinésia Francesa?" -tr -final
Analisando frase(s)...
-> Frase 1: Quem é o prefeito da capital da Polinésia Francesa?
--> Tipo: TipoFrase={tipo=quem, confianca=0.89, ids=[2]}
--> Voz: Voz.ATIVA
--> Termos Relevantes:
----> TR 0: [H:n|6| prefeito]
----> TR 1: [H:n|11| capital]
----> TR 2: [H:prop|16| Polinésia_Francesa]

```

**Comment by alencarrh** [comment]
Hi @DenisAraujo68 
I'll close this issue because its resolved now with the new confidence when calling dbpedia spotlight
