### ISSUE TITLE
Error message when running "-resposta" with "Os Pilares da Terra" question

### ISSUE THREAD

**Issue by DenisAraujo68** [Ensepro/ensepro-core#69]
**Describe the bug**
ENSEPRO returns an error when processing the question `"Quem escreveu o livro Os Pilares da Terra?"`

**To Reproduce**
1. run `ensepro -frase "Quem escreveu o livro Os Pilares da Terra?" -resposta`

**Log files**
[ensepro.log](https://github.com/Ensepro/ensepro-core/files/2841959/ensepro.log)

**Screenshots**

> root@ensepro:~# ensepro -frase "Quem escreveu o livro Os Pilares da Terra?" -resposta
> Analisando frase(s)... 
> 
> The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
> root@ensepro:~#

**Additional context**
- use DBPedia config

**Comment by alencarrh** [comment]
Hi @DenisAraujo68, problem resolved :)

```
root@ensepro:~# ensepro -frase "Quem escreveu o livro Os Pilares da Terra?" -resposta
Analisando frase(s)...

Melhores respostas:
0 11.333 [*os_pilares_da_terra | autor | ken_follett] - [10.000 0.333 1.000]

Lista de triplas candidatas a resposta:
0 11.333 [*os_pilares_da_terra | paginas | 816] - [10.000 0.333 1.000]
1 11.333 [*os_pilares_da_terra | editorabr | editora_rocco] - [10.000 0.333 1.000]
2 11.333 [*os_pilares_da_terra | isbnpt | 978] - [10.000 0.333 1.000]

```

**Comment by DenisAraujo68** [comment]
Perfect, @alencarrh !
And as you can see above, the embeddings finds the correct aswer!  \o/
