### ISSUE TITLE
The need of a Subquery to "capital da Austrália" isn't identified

### ISSUE THREAD

**Issue by DenisAraujo68** [Ensepro/ensepro-core#74]
**Describe the bug**
The subquery is required and the system doesn't identify this.

**To Reproduce**
1. run `ensepro -frase "Quantos habitantes tem a capital da Austrália?" -resposta`

**Expected behavior**
Identify that the subquery is required to the question.

**Log files**
[ensepro.log](https://github.com/Ensepro/ensepro-core/files/2851658/ensepro.log)

**Screenshots**
> 2019-02-11 12:57:52,770 - ensepro.cbc - INFO - Executando consulta e montagem das queries da frase
> 2019-02-11 12:57:52,770 - ensepro.cbc - INFO - Verificando necessidade de subquery.
> 2019-02-11 12:57:52,771 - ensepro.cln.complementos_nominais - INFO - Obtendo complementos nominais para frase: [Frase={id=1, palavras=[, , Quantos, habitantes, tem, , a, capital, , de, , a, Austrália, ], tipo=None, locucao_verbal=None, voz=None}]
> 2019-02-11 12:57:52,972 - ensepro.cln.complementos_nominais - INFO - Complemento nominal encontrado: [ComplementoNominal{nome=[H:n|8| capital], complemento=[H:prop|13| Austrália]}]
> 2019-02-11 12:57:52,972 - ensepro.cbc - INFO - Subquery não necessária.
> 2019-02-11 12:57:52,973 - ensepro.cbc - DEBUG - subquery resultado final: []

**Comment by alencarrh** [comment]
Hello @DenisAraujo68,

This is not a **bug** because this phrase contains only one **_complemento nominal_**
```
root@ensepro# ensepro -frase "Quantos habitantes tem a capital da Austrália?" -tr -cn -final
Analisando frase(s)...
-> Frase 1: Quantos habitantes tem a capital da Austrália?
--> Tipo: TipoFrase={tipo=quanto, confianca=0.92, ids=[3]}
--> Voz: Voz.ATIVA
--> Termos Relevantes:
----> TR 0: [H:n|4| habitantes]
----> TR 1: [H:n|8| capital]
----> TR 2: [H:prop|13| Austrália]
--> Complementos Nominais:
----> CN 0: capital + Austrália
```

and we have this rule:
https://github.com/Ensepro/ensepro-core/blob/b0c56ab704b14d9f2ed23e76600eaa367b5813d8/ensepro/cbc/__init__.py#L124-L130

**Comment by DenisAraujo68** [comment]
Registering that, after talking about this issue, we decided to change the current subquery detection algorithm so the need of subquery will be extended to cases where there are only one CN and a simple TR.
