### ISSUE TITLE
Problema enviar frases com parênteses ao PalavrasService

### ISSUE THREAD

**Issue by DenisAraujo68** [Ensepro/ensepro-core#9]
- Frase exemplo: Quem descobriu Ceres?

Após a frase ser atualizada, fica assim: ***Quem descobriu Ceres_(Mitologia)?***

Com isto, ocorre erro no PalavrasService.

### Fix

Remove tudo que estiver após o carácter sublinha (inclusive o próprio carácter sublinha).
No caso da frase acima, ficaria assim: ***Quem descobriu Ceres?***

**Comment by DenisAraujo68** [comment]
The problem was not solved.
We can see in the log that the string searched in ES is **ceres_mitologia** and should be **Ceres_(Mitologia)**.

Log: [ensepro.log](https://github.com/Ensepro/ensepro-core/files/2516334/ensepro.log)

**Comment by alencarrh** [comment]
This needs to be resolve in the triple's importing process.
